### ISSUE TITLE
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0

### ISSUE THREAD

**Issue by FarrukhXeb** [docknetwork/react-native-sdk#67]
**Environment**
OS: Windows
Android: v11 , API level 30
React Native v0.70.0
React: 18.1.0
Gradle v7.5.1

**Issue**
I'm trying to set up the Dock SDK in my React native starter project and going through some dependency issues. At first, it was unable to resolve the module  `@react-native-async-storage/async-storage` which I think should not be added on my end instead it should be a peer dependency. This was resolved but there came another issue which was Gradle build was not compatible.

```
yarn run v1.22.19
$ react-native run-android
info Starting JS server...
info Installing the app...

> Task :react-native-gradle-plugin:compileKotlin
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (10, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (119, 30): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (135, 26): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (157, 32): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (163, 31): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactExtension.kt: (171, 36): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\ReactPlugin.kt: (114, 48): 'reactRoot: DirectoryProperty' is deprecated. reactRoot was confusing and has been replace with root to point to your root project and reactNativeDir to point to the folder of the react-native NPM package
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (10, 37): 'ApplicationVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (11, 37): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (12, 37): 'LibraryVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (27, 51): 'BaseVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (130, 12): 'ApplicationVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (131, 12): 'LibraryVariant' is deprecated. Deprecated in Java
w: D:\office\appruvr\app\node_modules\react-native-gradle-plugin\src\main\kotlin\com\facebook\react\TaskConfiguration.kt: (251, 14): 'BaseVariant' is deprecated. Deprecated in Java

> Task :app:generatePackageList FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
6 actionable tasks: 6 executed

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.        
-----------
* Where:
Script 'D:\office\appruvr\app\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 131

* What went wrong:
Execution failed for task ':app:generatePackageList'.
> argument type mismatch

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 23s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Script 'D:\office\appruvr\app\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' line: 131

* What went wrong:
Execution failed for task ':app:generatePackageList'.
> argument type mismatch

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 23s

    at makeError (D:\office\appruvr\app\node_modules\execa\index.js:174:9)
    at D:\office\appruvr\app\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\office\appruvr\app\node_modules\react-native\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\office\appruvr\app\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
I've followed the instructions as documented in the repo. Let me know if there is something missing on my end.

**Comment by maycon-mello** [comment]
Thanks for reporting this issue @FarrukhXeb. This is related to the react-native version (0.70), and probably some installation steps missing too. We do support react-native 0.70, but there are few additional steps required.

We've created an example repository for that, and this should help you to fix this issue. Please check this one https://github.com/docknetwork/wallet-sdk-demo

Also, we will update our documentation to mention these additional installation steps required, and a link for this demo app.

Let us know if that works, thanks!
